export default [
    { id: 1, name: 'Цемент', description: 'orem ipsum dolor sit a consectetur adipisicing elit.' },
    { id: 2, name: 'Песок', description: 'Lorem ipsum dolor si consectetur adipisicing elit.' },
    { id: 3, name: 'Арматура', description: 'Lorem ipsum dolor sit amet, consectetur isicing elit.' },
    { id: 4, name: 'Пеноблоки', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 5, name: 'Пиломатериалы', description: 'Lorem ipsum dolor amet, consecteadipisicing elit.' },
    { id: 6, name: 'Гидроизоляция', description: 'Lorem ipsum dolo amet, consectetur adipisicing elit.' },
    { id: 7, name: 'Окна', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 8, name: 'Клей', description: 'Lorem ipsum dolor sit amet, consectetur adiping elit.' },
    { id: 9, name: 'Армированная сетка', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 10, name: 'Металл', description: 'Lorem ipsum dolor sit amet, constur adipisicing elit.' },
    { id: 11, name: 'Обои', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 12, name: 'Ламинат', description: 'Lorem ipsum dolit amet, consectetur adipisicing elit.' },
    { id: 13, name: 'Линолеум', description: 'Lorem ipsum dolor sit amet, consetur adipisicing elit.' },
    { id: 14, name: 'Шпаклёвка', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 15, name: 'Двери', description: 'Lorem ipsum dolor sit amet, consetur adipisicing elit.' },
    { id: 16, name: 'Трубы', description: 'Lorem ipsum dolor sit amet, consecte adipisicing elit.' },
    { id: 17, name: 'Потолки', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 18, name: 'Рамы', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 19, name: 'Пластик', description: 'Lorem ipsum dolor met, consectetur adipisicing elit.' },
    { id: 20, name: 'Бетон', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' },
    { id: 21, name: 'Дерево', description: 'Lorem ipsum dolor siet, consectetur adipisicing elit.' },
    { id: 22, name: 'Брусчатка', description: 'Lorem ipsum dolor samet, consectetur adipisicing elit.' },
    { id: 23, name: 'Паркет', description: 'Lorem ipsum dolor s, consectetur adipisicing elit.' },
    { id: 24, name: 'Крыша', description: 'Lorem ipsum dolor sit , consectetur adipisicing elit.' },
    { id: 25, name: 'Краска', description: 'Lorem ipsum or sit amet, consectetur adipisicing elit.' },
    { id: 26, name: 'Керамика', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.' }
  ];